### ISSUE TITLE
PROBLEME d'enregistrement sur inskape

### ISSUE THREAD

**Issue by KAKI47** [inkstitch/pyembroidery#100]
Ink/Stitch a rencontré une erreur inattendue. Ceci signifie qu'il s'agit d'un bug dans Ink/Stitch.

Si vous souhaitez aider, merci de 
- copier le message d'erreur en entier ci-dessous
- sauvegarder votre fichier svg
- créer un rapport d'erreur (issue) sur https://github.com/inkstitch/inkstitch/issues

Incluez la description de l'erreur et (si possible) le fichier svg.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (269) out of bounds (0, 255)Ink/Stitch a rencontré une erreur inattendue. Ceci signifie qu'il s'agit d'un bug dans Ink/Stitch.

Si vous souhaitez aider, merci de 
- copier le message d'erreur en entier ci-dessous
- sauvegarder votre fichier svg
- créer un rapport d'erreur (issue) sur https://github.com/inkstitch/inkstitch/issues

Incluez la description de l'erreur et (si possible) le fichier svg.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (269) out of bounds (0, 255)

**Comment by kaalleen** [comment]
Thank you for your error report. Your design file has too many color changes.
Please try to reduce color changes. For more information, have a look at our website:
https://inkstitch.org/docs/faq/#too-many-color-changes
